services:
  postgres:
    container_name: restapi
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: restapi
      POSTGRES_PASSWORD: mawuli302
      POSTGRES_USER: mawuli
      PGDATA: /data/postgres
    ports:
      - "5222:5432"

    restart: always

volumes:
  db:
